### ISSUE TITLE
添加帧缓冲快速改变模型外观的功能

### ISSUE THREAD

**Issue by longjj** [longjj/MineCube#15]
@mgsweet 

按照你之前的脑洞，使用[帧缓冲](https://learnopengl-cn.github.io/04%20Advanced%20OpenGL/05%20Framebuffers/)来实现各种炫酷效果？

**Comment by longjj** [comment]
Cool!  @mgsweet 

下次可以留意一下 project 的看板~

**Comment by mgsweet** [comment]
@longjj 噢噢这样，这东西不是我发起的毫无印象23333
