### ISSUE TITLE
Shadow 效果并没有体现出来

### ISSUE THREAD

**Issue by jianjieluo** [longjj/MineCube#17]
目前阴影部分并没有体现出来。

**Comment by Bowenwu1** [comment]
我们目标阴影效果是怎么样的？
是像MagicVoxel那样？
<img width="493" alt="2018-06-29 1 57 06" src="https://user-images.githubusercontent.com/16816766/42075633-5b1ecbf6-7ba4-11e8-9970-7d07b047a5e7.png">

**Comment by mgsweet** [comment]
嗯嗯

**Comment by mgsweet** [comment]
有没人觉得透明还挺好看的
