### ISSUE TITLE
Load Model occur bugs

### ISSUE THREAD

**Issue by Dashuaiguo** [longjj/MineCube#24]
Hi guys, I have tried to load `warrior.model` but I got sth very strange :(

![image](https://user-images.githubusercontent.com/22051195/42040742-e9ad1116-7b22-11e8-84f6-f439b7028133.png)

**Comment by Bowenwu1** [comment]
I will check it later today

**Comment by Bowenwu1** [comment]
不好意思，我目前还无法复现，请问能提供更多的细节给我吗？

**Comment by Dashuaiguo** [comment]
会不会是因为我的系统是64位的所以不支持？

**Comment by Dashuaiguo** [comment]
我在打开`warrior.model`后`add`时也是会出现间隔一行的情况。RT：

![bug2](https://user-images.githubusercontent.com/22051195/42087256-3092ee48-7bc8-11e8-8c7b-0d85927bde6d.PNG)

`undo`功能倒是正常的。

**Comment by mgsweet** [comment]
看上去貌似是方块与方块间间隔不正常所致，可以看到模型的方块树木是没有缺失的

**Comment by Bowenwu1** [comment]
@Dashuaiguo 十分感谢你的反馈！

**Comment by longjj** [comment]
@Bowenwu1 

我知道应该如何复现这个问题

将 sizePerCube 设置成 0.033， numPerEdge 设置成 25 之后，再进行编译发布， Load `warrior.model` 就会出现这个问题。

**Comment by Bowenwu1** [comment]
我成功复现了

**Comment by Bowenwu1** [comment]
[Bug]
当sizePerCube改为小于0.05时均会出现此问题
当sizePerCube改为大于0.05时导入会报out_of_range 错误

**Comment by mgsweet** [comment]
现在导入方块变透明了这个还需要解决一下

**Comment by 15331335** [comment]
透明水晶 feature 了解一下
![webwxgetmsgimg](https://user-images.githubusercontent.com/16065176/42315681-a2c013b8-807a-11e8-8e98-e4067b03c6fd.jpg)

**Comment by Bowenwu1** [comment]
你们改了什么？？

**Comment by longjj** [comment]
Fixed。 dump & load 的时候处理 alpha 值出现问题。

**Comment by Bowenwu1** [comment]
Fixed。
导入模型时，未更新缓冲区中的立方体位置数据
