### ISSUE TITLE
Display Text  support

### ISSUE THREAD

**Issue by longjj** [longjj/MineCube#7]
@15331335 

在展示前提供一个 bonus 的 display text support.

例如，显示一下提醒 “Press 'V' to view your art !”

**Comment by 15331335** [comment]
已添加文本渲染支持

**Comment by longjj** [comment]
Cool！ @15331335 

为什么又把  Done 移到了 In progress ？ （笑哭

如果感觉调试得差不多了的话可以把这个给 close 了然后移动到 Done 那里去了。我就先不动你的看板吧。

**Comment by mgsweet** [comment]
@longjj 因为我和他商议了下要改的地方昨天
